repos:
- hooks:
  - id: black
    language_version: python3.9
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
